### ISSUE TITLE
Affichage des prochains events des différentes communautés

### ISSUE THREAD

**Issue by glacasa** [mtg-france-asso/mtg-france-asso.github.io#10]
Je commence à réfléchir comment faire ça.

Étant donné que le site est statique, il faudra charger les données en JS
Et comme il y a plein de communautés, j'ai pas envie que chaque visiteur charge x flux RSS au chargement du site.

Je pense donc faire une appli qui chargera les données à intervale régulier, mettra les infos pertinentes dans un fichier statique et le déposera dans un storage public.

**Comment by tbolon** [comment]
C'est ce que je pensais proposer aussi. A noter que l'on pourra simplifier tout cela une fois les crédits azure débloqués (enfin j'espère).

En attendant, effectivement construire un aggrégateur de flux dans un api qui serait interrogé en JS me semble être la meilleure idée.

**Comment by glacasa** [comment]
Le repo pour l'agrégateur : 
https://github.com/mtg-france-asso/MeetupEventsAggregator

**Comment by glacasa** [comment]
Est-ce que quelqu'un sait comment en C# on peut parser une date au format "Thursday, September 15 at 6:30 PM" ?

**Comment by glacasa** [comment]
Ça marche avec 2 m pour les minutes
DateTime.ParseExact(dateMatch.Groups[1].Value, "dddd, MMMM d \"at\" h:mm tt", CultureInfo.InvariantCulture);

Et histoire de me prendre la tête à chercher un bug qui n'existe pas, il a fallu que les 2 seuls meetups prévus sont à la même date et même heure 😅
https://www.meetup.com/fr-FR/azug-fr/events/287453929/
https://www.meetup.com/fr-FR/mtg-lille/events/288279042/

**Comment by tbolon** [comment]
> Ça marche avec 2 m pour les minutes

Effectivement, mais "m" marchera dans tous les cas pour les minutes (qu'ils mettent le 0 si < 10 ou non) : 6:07 PM et 6:7 PM marcheront.

"mm" ne marchera que si le 0 est toujours présent pour les minutes (07 = OK ; 7 = KO).

**Comment by glacasa** [comment]
Le flux agrégé est en ligne :
https://mtg-meetupeventsaggregator.apps.pericia.fr/api/events

ça renvoie les 10 prochains évènements des différentes communautés

On peut changer le nombre max en passant un param `limit`
https://mtg-meetupeventsaggregator.apps.pericia.fr/api/events?limit=50

**Comment by tagazok** [comment]
Pour info Nathan avait fait un truc pas mal pour https://www.devcongalaxy.io/#/
Toutes les nuits une Azure Functions tournait et appelait les flux rss puis poussait les prochains events dans un json qui était sur le repo du site (https://github.com/DevConGalaxy/DevConGalaxy.github.io/blob/master/src/assets/meetupsdata.json)
Bon elle a arrété de tourner depuis un moment mais ça marchait plutôt bien :)
